<a href="https://colab.research.google.com/github/Marin0306/Carpeta-de-evidencias/blob/main/artificialnet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
#Artificial Neural Network
#Importing the libraries
import numpy as np
import pandas as pd
import tensorflow as tf
import os
tf.__version__
import matplotlib.pyplot as plt
import tensorflow.experimental.numpy as tnp
import timeit

print("Using TensorFlow version %s" % tf.__version__)

Using TensorFlow version 2.12.0


In [19]:
mainpath = 'csv'
filename = 'Churn_Modelling.csv'
fullpath = os.path.join(mainpath,filename)

In [20]:
dataset = pd.read_csv(fullpath)
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values
print(X)
print(y)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]
[1 0 1 ... 1 1 0]


In [21]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [22]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer (transformers=[('encoder', OneHotEncoder(), [1])], 
remainder='passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [23]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2,
random_state = 0)

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [25]:
ann = tf.keras.models.Sequential()

In [26]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [27]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [28]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [29]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics =['accuracy'])

In [30]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 3ms/step - loss: 0.5693 - accuracy: 0.7716
Epoch 2/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4828 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.4571 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 1s 2ms/step - loss: 0.4394 - accuracy: 0.7984
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4265 - accuracy: 0.8146
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4182 - accuracy: 0.8169
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4130 - accuracy: 0.8181
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4090 - accuracy: 0.8211
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4052 - accuracy: 0.8232
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4018 - accura

In [31]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1,
50000]])) > 0.5)

1/1 [==============================] - 0s 203ms/step
[[False]]


In [32]:
y_pred = ann.predict(X_test)
y_pred =(y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),
y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 4ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1497   98]
 [ 190  215]]


0.856